version: '3.8.0'
services:
  api:
    build: ./backend
    container_name: api.c
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017
      - PORT=3000
